openapi: 3.1.0
info:
  version: 1.0.0
  title: Byte&Bite app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    A RESTful API for managing recipes.
    Supports user registration, authentication,
    and password reset via email.
tags:
  - name: Categories
    description: Operations about categories.
  - name: Ingredients
    description: Operations about ingredients.
  - name: Auth
    description: Auth operations.
servers:
  - url: http://127.0.0.1:3000
paths:
  /categories:
    get:
      $ref: '../swagger/paths/categories/get.yaml'
  /ingredients:
    get:
      $ref: '../swagger/paths/ingredients/get.yaml'


  /recipes:
    get:
      $ref: '../swagger/paths/recipes/get.yaml'

  /recipes/{id}:
    get:
      $ref: '../swagger/paths/recipes/getById.yaml'

  /recipes/add-recipe:
    post:
      $ref: '../swagger/paths/recipes/postAddRecipe.yaml'

  /recipes/profile/own:
    get:
      $ref: '../swagger/paths/recipes/getOwn.yaml'

  /recipes/profile/favorites:
    get:
      $ref: '../swagger/paths/recipes/favorites/getFavorites.yaml'
    post:
      $ref: '../swagger/paths/recipes/favorites/postFavorites.yaml'

  /recipes/profile/favorites/{recipeId}:
    delete:
      $ref: '../swagger/paths/recipes/favorites/deleteFavorites.yaml'


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
