Recipe:
  type: object
  required:
    - _id
    - name
    - decr
    - cookiesTime
    - category
    - ingredients
    - ingredientAmount
    - instruction
    - owner
  properties:
    _id:
      type: string
      example: "65d7e8a4b9c3d12a5d8e9b74"
    name:
      type: string
      maxLength: 64
      example: "Chocolate Cake"
    decr:
      type: string
      maxLength: 200
      example: "Rich and moist cake perfect for celebrations."
    cookiesTime:
      type: integer
      minimum: 1
      maximum: 360
      example: 45
    cals:
      type: integer
      minimum: 1
      maximum: 10000
      nullable: true
      example: 320
    category:
      type: string
      example: "dessert"
    ingredients:
      type: array
      items:
        $ref: './ingredient.yaml'
    ingredientAmount:
      type: integer
      minimum: 2
      maximum: 16
      example: 5
    instruction:
      type: string
      maxLength: 1200
      example: "Mix all ingredients and bake at 180°C for 35 minutes."
    recipeImg:
      type: string
      format: uri
      nullable: true
      example: "https://example.com/images/recipe.jpg"
    owner:
      type: string
      example: "65d123abc9876543210fedcb"
    isFavorite:
      type: boolean
      nullable: true
      example: true
    createdAt:
      type: string
      format: date-time
      example: "2024-12-01T14:23:00Z"
    updatedAt:
      type: string
      format: date-time
      example: "2024-12-05T11:00:00Z"
  example:
    _id: "6462a8f74c3d0ddd28898084"
    name: "Japanese gohan rice"
    category: "Side"
    owner: "64c8d958249fae54bae90bb9"
    decr: "A staple in Japanese cuisine, Gohan rice is a short-grain, sticky rice…"
    cookiesTime: 30
    instruction: "STEP 1\nRinsing and soaking your rice is key to achieving the perfect …"
    ingredients:
      - id: "640c2dd963a319ea671e3892"
        measure: "300g"
      - id: "640c2dd963a319ea671e37f7"
        measure: "1 tbs"
      - id: "640c2dd963a319ea671e3889"
        measure: "Garnish"
      - id: "640c2dd963a319ea671e3770"
        measure: "Garnish"
    recipeImg: "https://ftp.goit.study/img/so-yummy/preview/Japanese%20gohan%20rice.jpg"
    createdAt: "2023-03-11T19:25:33.247+00:00"
    updatedAt: "2023-04-14T20:02:28.085+00:00"
